parent(michael, john).
parent(michael, emily).
parent(michael, sophia).
parent(john, anna).
parent(john, david).
parent(john, sarah).
parent(emily, jacob).
parent(emily, olivia).
parent(emily, ethan).
parent(sophia, lucas).
parent(sophia, mia).
parent(sophia, liam).
parent(anna, sophie).
parent(anna, benjamin).
parent(anna, emma).